New Keywords: break-at (foreach) / count (setvar)
Mistralys/mailcode pull request #11
Opened 2023-05-03 15:14 UTC by oboecker

This branch introduces two new keywords:
- break-at for "for" loops
-- this expects a parameter after the "break-at:" keyword
- count for "setvar" assignments
-- this expects a parameter after the "count:" keyword

For this purpose, a new Method has been introduced to obtain the Token for a given keyword. The logic is quite simple, but I am not sure how it can be tested.
Both keywords are realized using Traits, and rely on the token mechanism for validation and processing.

2023-05-08 12:37 UTC, Mistralys commented on src/Mailcode/Traits/Commands/Validation/BreakAtTrait.php
This has `use phpDocumentor\Descriptor\Interfaces\FunctionInterface;` which I suspect is a mistake - at least it should not be used here, as it is a dev-only library.

2023-05-08 12:38 UTC, Mistralys commented on src/Mailcode/Traits/Commands/Validation/CountTrait.php
This has `use phpDocumentor\Descriptor\Interfaces\FunctionInterface;` as well, which should be removed.

2023-05-08 12:38 UTC, Mistralys commented on src/Mailcode/Traits/Commands/Validation/NoTrackingTrait.php
There are some phpDocumentor use statements here as well.

2023-05-08 12:40 UTC, Mistralys commented on src/Mailcode/Commands/CommonConstants.php
This has whitespace changes only?

2023-05-08 12:42 UTC, Mistralys requested changes
I had a look at the files, beyond the phpDocumentor `use` statements that should be removed, it looks good!

2023-05-08 13:41 UTC, oboecker commented on src/Mailcode/Traits/Commands/Validation/NoTrackingTrait.php
My guess is that this is the original source, as I C&P the other Traits from this one.

2023-05-08 14:03 UTC, Mistralys commented on src/Mailcode/Traits/Commands/Validation/NoTrackingTrait.php
Ah, then it was most likely my bad :|

2023-06-16 05:51 UTC, Mistralys approved these changes

2023-06-16 06:05 UTC, merged